### ISSUE TITLE
=。=可以支持一下AE2020吗

### ISSUE THREAD

**Issue by wexs** [svga/SVGA-AEConverter#11]

**Comment by errnull** [comment]
即将支持

**Comment by wexs** [comment]
@errnull =。=请问现在还有计划更新插件吗～

**Comment by lgengsy** [comment]
@liveme @errnull 大佬跪求更新啊。手馋更新了Mac系统，Ae2019不能用了,更新了AE2020，现在插件不能用了。

**Comment by PonyCui** [comment]
@lgengsy 我推进一下

**Comment by liveme** [comment]
> @liveme @errnull 大佬跪求更新啊。手馋更新了Mac系统，Ae2019不能用了,更新了AE2020，现在插件不能用了。

不能用具体什么表现？在macOS Big Sur 11.2.1的AE 2020测试是没有问题的

**Comment by lgengsy** [comment]
我这边是 macOS Big Sur 11.2.2，以下是错误提示及相关的信息
<img width="281" alt="企业微信截图_f2cc9bcb-17ae-46d0-9bb1-1a76cfed1cfe" src="https://user-images.githubusercontent.com/3983443/109774315-2c1dd780-7c3b-11eb-9277-0867772dca4a.png">
<img width="251" alt="企业微信截图_705d72d7-3970-4a2e-9a4b-2b3112196f99" src="https://user-images.githubusercontent.com/3983443/109774346-3344e580-7c3b-11eb-9569-9d1d293e7297.png">
<img width="595" alt="企业微信截图_284b7572-4889-4004-ba1f-94884b2704e2" src="https://user-images.githubusercontent.com/3983443/109774369-38a23000-7c3b-11eb-9a42-6ae3f8005920.png">
大佬辛苦了

**Comment by lgengsy** [comment]
也可以发下你使用的AE 版本信息 ，我这更新到这个版本的AE试试看。

**Comment by lgengsy** [comment]
我新建一个项目，拖几张图片进去，直接导出SVGA是能导出的。我之前做的AE效果，导出SVGA的时候出现了上边的问题。

**Comment by liveme** [comment]
@lgengsy 目前测试发现升级到17.6在某些使用了PSD图层的项目会出现这个问题，可能跟PSD的顺序、命名这些有间接关系，但具体原因尚未定位到。你那个项目是不是使用了多个PSD？在弹出错误提示框时，下面的渲染队列显示的图层有什么特殊吗？
可以试试以前做的没有使用PSD图层的AE项目看看，或者暂时退回 AE 17.5，这个版本应该没问题。

**Comment by lgengsy** [comment]
好的，大佬我们试试。

**Comment by lgengsy** [comment]
需要我们现在的源文件可以在SVGA的那个群里找下我。我在里边。源文件可以给你们，方便你们排查问题。

**Comment by lgengsy** [comment]
问题文件已发 @liveme QQ邮箱查收

**Comment by liveme** [comment]
@lgengsy 确实是PSD的问题，某些PSD文件中含有Unicode编码，AE 17.6中的`renderQueue.render()`在渲染图层时无法处理这些Unicode编码。短期内暂无计划支持这个问题，感谢你的使用反馈！
以下是针对这个问题的使用建议：
1. 无论新旧版AE，都不建议使用PSD图层，更优的做法是先把PSD导出为jpg和png再导入AE项目。因为即使在旧版AE没有该错误，转译器在处理PSD图层的压缩时也会因为系统环境等因素而产生不太稳定的svga文件大小问题；
2. 暂时退回AE 17.5以下的版本使用（未经大范围测试）；

**Comment by PonyCui** [comment]
已支持AE2021
