### ISSUE TITLE
Can't install svga after effects converter on windows

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [svga/SVGA-AEConverter#14]
That Error fires on installing svga after effects converter on windows
![image](https://user-images.githubusercontent.com/52201392/99044877-22dc0280-2599-11eb-90c6-cafeb0f6d879.png)

**Comment by whatnowangga** [comment]
How do you solved this issue?

**Comment by k00re** [comment]
> How do you solved this issue?

?? pleas tell me

**Comment by srb2410** [comment]
Hello,
There might be 2 causes.

1.Your After Effects Version is not compatible.
2.You aren't running it as administrator
Solutions:
3.Change Compatible AE version in extension installed files
Try Running as administrator

**Comment by asankar911** [comment]
Hello guys, did you find a solution for this issue?
I am using windows 11 with adobe AE 2022
Kindly advise
![svga error](https://github.com/svga/SVGA-AEConverter/assets/41984287/16f9bdc4-79c5-44da-a35b-08b9664e55e0)
