### ISSUE TITLE
似乎不兼容 After Effects 最新的 2021 版本

### ISSUE THREAD

**Issue by shuuiran** [svga/SVGA-AEConverter#15]
在最新的After Effects 18.0.1下，「扩展」中不会出现SVGA-AEConverter
macOS与Windows下都是如此。

**Comment by nickkwok** [comment]
After Effects 18.0.0（Build 39），窗口-扩展 菜单中无法显示 SVGA-AEConverter。
MacOS 11.2.3 (20D91)
用 ZXP Installer 重新安装，会提示没有兼容的软件。

**Comment by PonyCui** [comment]
已支持AE2021

**Comment by shuuiran** [comment]
太感謝了，之前一直被迫保留2020版本用於輸出。

**Comment by PonyCui** [comment]
使用最新版本的 zxp 安装，5小时前的版本有点问题。

**Comment by shuuiran** [comment]
了解
