### ISSUE TITLE
似乎不兼容 After Effects 最新的 2022 版本

### ISSUE THREAD

**Issue by shuuiran** [svga/SVGA-AEConverter#17]
Adobe又更新版本了呢
跟去年的問題一致
https://github.com/svga/SVGA-AEConverter/issues/15

**Comment by onlylhf** [comment]
可以尝试修改 
C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\com.errnull.SVGAConverter_AE\CSXS\manifest.xml
文件内：
`
<Host Name="AEFT" Version="[13.0,18.9]"/>
<Host Name="AEFX" Version="[13.0,18.9]"/>`
为
`
<Host Name="AEFT" Version="[13.0,22.4]"/>
<Host Name="AEFX" Version="[13.0,22.4]"/>`

可以兼容使用2022版AE

**Comment by logicool** [comment]
@onlylhf 大佬，mac版本的怎么办呢？

**Comment by shuuiran** [comment]
@logicool 一样也是用上面大佬的方法，路径是 /Library/Application Support/Adobe/CEP/extensions/com.errnull.SVGAConverter_AE/CSXS/manifest.xml

**Comment by logicool** [comment]
> @logicool 一样也是用上面大佬的方法，路径是 /Library/Application Support/Adobe/CEP/extensions/com.errnull.SVGAConverter_AE/CSXS/manifest.xml

我目前用zxp installer安装不上，需要手动安装后再修改文件。

**Comment by PonyCui** [comment]
已支持
