### ISSUE TITLE
关于形状使用渐变输出显示不来的问题

### ISSUE THREAD

**Issue by RRRRRye** [svga/SVGA-AEConverter#4]
你好，我想问一下，我在AE里面用了钢笔钩画了一个形状出来 用渐变色上色 然后输出成svga，但是却显示不出来那个形状，我换成纯色块后，重新输出就可以显示出来了。想问一下，是不支持渐变色吗？还是说有其他的方法呢？

**Comment by PonyCui** [comment]
是的，暂时不支持渐变色，你可以将形状转换为位图。

**Comment by RRRRRye** [comment]
可是这样会导致文件很大，有什么方法可以压缩svga的大小吗？

**Comment by PonyCui** [comment]
单个形状转换为位图并不会导致文件变大，除非你有几百个形状。

**Comment by RRRRRye** [comment]
在AE里怎么把形状转化为位图呢？我不太懂你的意思

**Comment by PonyCui** [comment]
我建议是使用 PNG 作为单个图层去做动画

**Comment by RRRRRye** [comment]
好的～谢谢～你真好～
